### ISSUE TITLE
Color data out of range

### ISSUE THREAD

**Issue by Tranvick** [junyanz/interactive-deep-colorization#2]
I'm not sure if this is an real issue, it's just warning, but it can be a sign of some bigger problem. 
I get this very often:
> ('mouse press', PyQt4.QtCore.QPoint(338, 265))
/home/tranvick/.local/lib/python2.7/site-packages/skimage/color/colorconv.py:985: UserWarning: Color data out of range: Z < 0 in 22149 pixels
  warn('Color data out of range: Z < 0 in %s pixels' % invalid[0].size)

**Comment by richzhang** [comment]
This is okay, it happens. Thanks!

**Comment by blshkv** [comment]
I'm seeing a similar issue. colorconv.py belongs to sci-libs/scikits_image-0.12.3:

```
Setting ab cluster centers in layer: pred_ab
Setting upsampling layer kernel: pred_313_us
test_imgs/mortar_pestle.jpg
scale = 2.000000
Traceback (most recent call last):
  File "/home/Downloads/ideepcolor/ui/gui_palette.py", line 85, in mousePressEvent
    self.update_ui(color_id)
  File "/home/Downloads/ideepcolor/ui/gui_palette.py", line 78, in update_ui
    color = self.colors[color_id]
TypeError: 'NoneType' object has no attribute '__getitem__'
('mouse press', PyQt4.QtCore.QPoint(327, 241))
/usr/lib64/python2.7/site-packages/skimage/color/colorconv.py:901: UserWarning: Color data out of range: Z < 0 in 21507 pixels
  warn('Color data out of range: Z < 0 in %s pixels' % invalid[0].size)
set_ab x, y = 160, 159
process add Point
('image_size', (512, 432))
add (point) with win_size 512.000, load_size 256.000
add user edit 1

Traceback (most recent call last):
  File "/home/Downloads/ideepcolor/ui/gui_draw.py", line 209, in change_color
    x, y = self.scale_point(pos)
  File "/home/Downloads/ideepcolor/ui/gui_draw.py", line 185, in scale_point
    x = int((pnt.x() - self.dw) / float(self.win_w) * self.load_size)
AttributeError: 'bool' object has no attribute 'x'
('mouse press', PyQt4.QtCore.QPoint(119, 298))

```

**Comment by junyanz** [comment]
@blshkv  I cannot reproduce the `AttributeError: 'bool' object has no attribute 'x'` bug you mentioned. Could you tell me how to produce it?
