### ISSUE TITLE
Failed to load module "appmenu-gtk-module"

### ISSUE THREAD

**Issue by JackMechem** [junyanz/interactive-deep-colorization#87]
## Hello
I am running Arch Linux and I am running into this error
```/usr/lib/python3.9/site-packages/matplotlib/backends/qt_editor/figureoptions.py:11: MatplotlibDeprecationWarning:
The support for Qt4  was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
  from matplotlib.backends.qt_compat import QtGui
[win_size] = 512
[image_file] = test_imgs/mortar_pestle.jpg
[gpu] = 0
[cpu_mode] = True
[color_prototxt] = ./models/reference_model/deploy_nodist.prototxt
[color_caffemodel] = ./models/reference_model/model.caffemodel
[dist_prototxt] = ./models/reference_model/deploy_nopred.prototxt
[dist_caffemodel] = ./models/reference_model/model.caffemodel
[color_model] = ./models/pytorch/caffemodel.pth
[backend] = pytorch
[pytorch_maskcent] = False
[load_size] = 256
ColorizeImageTorch instantiated
path = ./models/pytorch/caffemodel.pth
Model set! dist mode?  False
ColorizeImageTorch instantiated
path = ./models/pytorch/caffemodel.pth
Model set! dist mode?  True

**ERROR STARTS HERE**

Gtk-Message: 10:54:48.068: Failed to load module "appmenu-gtk-module"
b'test_imgs/mortar_pestle.jpg'
Traceback (most recent call last):
  File "/home/jack/interactive-deep-colorization/ideepcolor.py", line 78, in <module>
    window = gui_design.GUIDesign(color_model=colorModel, dist_model=distModel,
  File "/home/jack/Cool/interactive-deep-colorization/ui/gui_design.py", line 112, in __init__
    self.drawWidget.init_result(img_file)
  File "/home/jack/interactive-deep-colorization/ui/gui_draw.py", line 48, in init_result
    self.read_image(image_file.encode('utf-8'))  # read an image
  File "/home/jack/interactive-deep-colorization/ui/gui_draw.py", line 73, in read_image
    im_bgr = cv2.imread(image_file)
TypeError: Can't convert object of type 'bytes' to 'str' for 'filename' 
```
I have installed all of the listed dependencies. I am using pytorch because I could not get Caffe installed on my system (pytorch was easier). I assume the error is handling with the UI but I am not sure what it is caused by.

**Comment by Benitoite** [comment]
https://github.com/junyanz/interactive-deep-colorization/blob/fa69e9c1d65daacae7ae83c4f85a988d3862953e/ui/gui_draw.py#L219

The `unicode` and `str` types are no longer interchangeable in *python3* as they were previously.
